"""Runner-adapter normalization from legacy aliases to atomic IDs."""

from __future__ import annotations

from .runner_adapter_chain_of_thought_reasoning_v1 import RUNNER_ADAPTER_CHAIN_OF_THOUGHT_REASONING_V1
from .runner_adapter_chain_of_thought_self_consistency_reasoning_v1 import (
    RUNNER_ADAPTER_CHAIN_OF_THOUGHT_SELF_CONSISTENCY_REASONING_V1,
)
from .runner_adapter_react_code_agent_with_task_tools_v1 import (
    RUNNER_ADAPTER_REACT_CODE_AGENT_WITH_TASK_TOOLS_V1,
)
from .runner_adapter_react_reasoning_text_loop_no_tools_v1 import (
    RUNNER_ADAPTER_REACT_REASONING_TEXT_LOOP_NO_TOOLS_V1,
)
from .runner_adapter_single_path_reasoning_v1 import RUNNER_ADAPTER_SINGLE_PATH_REASONING_V1
from .runner_adapter_tree_of_thoughts_generalized_recursive_reasoning_v1 import (
    RUNNER_ADAPTER_TREE_OF_THOUGHTS_GENERALIZED_RECURSIVE_REASONING_V1,
)
from .runner_adapter_tree_of_thoughts_search_reasoning_v1 import (
    RUNNER_ADAPTER_TREE_OF_THOUGHTS_SEARCH_REASONING_V1,
)


_RUNNER_ADAPTER_ALIAS_TO_ATOMIC_ID = {
    RUNNER_ADAPTER_SINGLE_PATH_REASONING_V1: RUNNER_ADAPTER_SINGLE_PATH_REASONING_V1,
    RUNNER_ADAPTER_CHAIN_OF_THOUGHT_REASONING_V1: RUNNER_ADAPTER_CHAIN_OF_THOUGHT_REASONING_V1,
    RUNNER_ADAPTER_CHAIN_OF_THOUGHT_SELF_CONSISTENCY_REASONING_V1: RUNNER_ADAPTER_CHAIN_OF_THOUGHT_SELF_CONSISTENCY_REASONING_V1,
    RUNNER_ADAPTER_REACT_CODE_AGENT_WITH_TASK_TOOLS_V1: RUNNER_ADAPTER_REACT_CODE_AGENT_WITH_TASK_TOOLS_V1,
    RUNNER_ADAPTER_REACT_REASONING_TEXT_LOOP_NO_TOOLS_V1: RUNNER_ADAPTER_REACT_REASONING_TEXT_LOOP_NO_TOOLS_V1,
    RUNNER_ADAPTER_TREE_OF_THOUGHTS_SEARCH_REASONING_V1: RUNNER_ADAPTER_TREE_OF_THOUGHTS_SEARCH_REASONING_V1,
    RUNNER_ADAPTER_TREE_OF_THOUGHTS_GENERALIZED_RECURSIVE_REASONING_V1: RUNNER_ADAPTER_TREE_OF_THOUGHTS_GENERALIZED_RECURSIVE_REASONING_V1,
    "single": RUNNER_ADAPTER_SINGLE_PATH_REASONING_V1,
    "cot": RUNNER_ADAPTER_CHAIN_OF_THOUGHT_REASONING_V1,
    "cot_sc": RUNNER_ADAPTER_CHAIN_OF_THOUGHT_SELF_CONSISTENCY_REASONING_V1,
    "react": RUNNER_ADAPTER_REACT_CODE_AGENT_WITH_TASK_TOOLS_V1,
    "react_codeagent": RUNNER_ADAPTER_REACT_CODE_AGENT_WITH_TASK_TOOLS_V1,
    "react_text": RUNNER_ADAPTER_REACT_REASONING_TEXT_LOOP_NO_TOOLS_V1,
    "tot": RUNNER_ADAPTER_TREE_OF_THOUGHTS_SEARCH_REASONING_V1,
    "tot_gen": RUNNER_ADAPTER_TREE_OF_THOUGHTS_GENERALIZED_RECURSIVE_REASONING_V1,
}


def normalize_runner_adapter_id(value: str) -> str:
    """Normalize legacy alias into one atomic runner-adapter ID."""
    key = str(value or "").strip()
    if key not in _RUNNER_ADAPTER_ALIAS_TO_ATOMIC_ID:
        raise ValueError(f"Unsupported runner adapter id/name: {value}")
    return _RUNNER_ADAPTER_ALIAS_TO_ATOMIC_ID[key]
